### PR TITLE
rpc: allow transfer of exception when method not found

### PR DESCRIPTION
**Pull request by jonEbird**
When the method is not actually defined in the remote RPC class we get an
AttributeError exception thrown. We should catch this as well to correctly
identify the NoMethodError case, then allow for that exception to be sent
over to be properly handled by the caller.

### CODE REVIEW

**Comment by dsiroky** [comment]
Hi, thank you for the PR. You pointed to a nest of bugs I missed. Please try this commit instead and let me know if it works for you: https://github.com/dsiroky/snakemq/commit/fcdabac34bc6fa5bcf5bba9000c52f6ffa5343fe

**Comment by jonEbird** [comment]
I tried your commit and is working as advertised. Thanks!

**Comment by jonEbird** [comment]
Any chance we'll see your latest fix in a v1.6 release soon?

**Comment by dsiroky** [comment]
Probably at the end of this week. Use the master branch if you don't mind.

**Pull request closed without merging**
